[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8000} -t public"
